server:
  port: 9005

spring:
  application:
    name: testall

  redis:
    host: 39.96.160.110

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-6kot9g5e.cd.tencentcdb.com:10007/Docker_User?characterEncoding=utf-8&useSSL=true
    #    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
    username: root
    password: zby123456


  jpa:
    database-platform:
      # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
      org.hibernate.dialect.MySQL5InnoDBDialect
    database: MySQL
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update