server:
  port: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: core

  servlet:
    multipart:
      max-file-size: 10MB


  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-6kot9g5e.cd.tencentcdb.com:10007/newplan?characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
    username: root
    password: zby123456

  redis:
    host: 39.96.160.110

  rabbitmq:
    host: 106.54.231.246

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎

    database: MySQL
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  mail:
    host: smtp.qq.com
    username: 381016296@qq.com
    password: jddvtkjkdlvfbiec
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true

    #freemarker配置



### QQ
constants:
  qqAppId: 101523068
  qqAppSecret: f821795af3380faf8099365da5333772
  qqRedirectUrl: http://zby1.wezoz.com/user/QQLogin
  ### 微信
  weCatAppId:
  weCatAppSecret:
  weCatRedirectUrl:

#熔断保护机制
feign:
  hystrix:
    enabled: true
#feign默认调用时间是1s，防止文件还未上传完成就遭到熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 20000


page:
  size: 10

jwt:
  config:
    key: zby
    expire: 86400000

#设置一个邮件发送人
lance:
  mail:
    sender: 381016296@qq.com

sms:
  time: 10

UserInfo:
  Photo: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1571302471&di=4ce44558200bd366f7a56c646a24ec45&imgtype=jpg&er=1&src=http%3A%2F%2Fimg.qqzhi.com%2Fuploads%2F2018-11-30%2F021340324.jpg
  Nickname: ZBY-
  Gender: 【未知】
