server:
  port: 9111

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: sms

  rabbitmq:
    host: ****
    password: ****
    username: ****
    port: ****

aliyun:
  sms:
    accessKeyId : ****
    accessKeySecret : ****
    templateCode: ****
    signName: ****
