server:
  port: 9007

spring:
  application:
    name: myTime

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-6kot9g5e.cd.tencentcdb.com:10007/time?characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
    username: root
    password: zby123456


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎

    database: MySQL
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

page:
  size: 4